Foreground yes
DatabaseDirectory /var/lib/clamav
LocalSocket /run/clamav/clamd.sock
LocalSocketMode 600
FixStaleSocket yes
PidFile /run/clamav/clamd.pid
LogFile /tmp/clamav/clamd.log
LogTime yes
LogFileMaxSize 10M
LogRotate yes
TemporaryDirectory /tmp/clamav

MaxThreads 4
MaxQueue 8
ReadTimeout 900
CommandReadTimeout 30
SelfCheck 300
MaxScanTime 900000
StreamMaxLength 2000M
MaxScanSize 2000M
MaxFileSize 2000M
MaxRecursion 32
MaxFiles 10000
AlertExceedsMax yes
ConcurrentDatabaseReload no
